meta_product_name: "sava"
meta_title: "sava"
meta_description: "sava connects people in mid-/long-term medical treatment with their family and friends. It is the first application specifically designed for people in these difficult situations improving their daily life."
meta_image: "cover.png" # should exist in `app/assets/images/`
